name: deno-build
on:
  push:
  pull_request:

jobs:


  npm-publish:
    name: deno-build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.3.0]

    env:
      DENO_DIR: ${GITHUB_WORKSPACE}/deno_cache

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Deno Version Latest Stable
      uses: denoland/setup-deno@v1
      with:
        deno-version: vx.x.x

    - uses: actions/cache@v3
      with:
        path: ${{ env.DENO_DIR }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/deps.ts') }}
        restore-keys: |
          ${{ runner.os }}-node-
    # Scan the code for syntax errors and style issues. If
    # you want to use a custom linter configuration you can add a configuration file with --config <myconfig>
    - name: Deno Lint
      run: deno lint
      continue-on-error: true

    - name: Deno FMT Check Module
      run: deno fmt --check
      continue-on-error: true

    - name: Build Deno Module
      run: deno run --allow-read --allow-write --reload src/mod.ts 
